# Generated by Django 5.2 on 2025-04-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved_bag',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
