# Generated by Django 3.2.25 on 2025-04-01 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='growguide',
            old_name='name',
            new_name='guide_title',
        ),
        migrations.RenameField(
            model_name='growguide',
            old_name='description',
            new_name='instructions',
        ),
    ]
