# Generated by Django 3.2.25 on 2025-04-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_auto_20250401_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='growguide',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='growguide',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
