# Generated by Django 3.2.25 on 2025-04-07 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_auto_20250407_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='growguide',
            options={'ordering': ['step_no']},
        ),
        migrations.RenameField(
            model_name='growguide',
            old_name='priority',
            new_name='step_no',
        ),
    ]
