# Generated by Django 3.2.25 on 2025-03-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='attendee_qty',
            field=models.IntegerField(default=0),
        ),
    ]
