# Generated by Django 3.2.25 on 2025-03-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video_url',
        ),
    ]
