# Generated by Django 3.2.25 on 2025-03-22 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='access_granted',
            new_name='confirmed',
        ),
    ]
