# Generated by Django 3.2.25 on 2025-04-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_access_granted_enrollment_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Enrolled', 'Enrolled'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
    ]
