# Generated by Django 5.2 on 2025-04-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20250416_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='spots_booked',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
