# Generated by Django 3.2.25 on 2025-04-16 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_enrollment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
