# Generated by Django 5.2 on 2025-04-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_enrollment_enrolled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='start_datetime',
            field=models.DateTimeField(blank=True, help_text='The date and time the course starts', null=True),
        ),
    ]
