# Generated by Django 3.2.25 on 2025-04-22 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_start_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
    ]
